# JVM settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot

# Minecraft & Loaders
minecraft_version=26.2
fabric_loader_version=0.19.2
neoforge_version=26.2.0.1-beta
fabric_api_version=0.152.1+26.2
loom_version=1.16-SNAPSHOT

# Config & ModMenu
yacl_version=3.9.4+26.2-fabric
yacl_version_neoforge=3.9.4+26.2-neoforge
modmenu_version=20.0.0-beta.2

# Mod metadata
mod_version=5.3
mod_id=fps_overlay
mod_name=Fps Overlay
mod_description=Displays a minimal performance overlay.
mod_author=Hicham
mod_license=MIT
maven_group=net.hicham
archives_base_name=FpsOverlay
mod_homepage=https://modrinth.com/project/j0IQ4hjv
mod_sources=https://github.com/hihcam/fps-overlay-Fabric

# Publishing project IDs (tokens are in ~/.gradle/gradle.properties)
modrinth_project_id=j0IQ4hjv
curseforge_project_id=1341801
