plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

repositories {
    mavenCentral()
    maven { url = "https://maven.isxander.dev/releases" }
    maven { url = "https://maven.quiltmc.org/repository/release/" }
    maven { url = "https://maven.neoforged.net/releases/" }
    maven { url = "https://api.modrinth.com/maven" }
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${project.archives_base_name}-neoforge"
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = [
                'src/main/java',
                '../src/main/java'
            ]
            exclude 'net/hicham/fps_overlay/fabric/**'
        }
        resources {
            srcDirs = [
                'src/main/resources',
                '../src/main/resources'
            ]
            exclude 'fabric.mod.json'
        }
    }
}

dependencies {
    // YACL (NeoForge)
    implementation "maven.modrinth:yacl:${project.yacl_version_neoforge}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version,
               "minecraft_version": project.minecraft_version,
               "mod_id": project.mod_id,
               "mod_name": project.mod_name,
               "mod_description": project.mod_description,
               "mod_author": project.mod_author,
               "mod_license": project.mod_license,
               "neoforge_version": project.neoforge_version,
               "mod_homepage": project.mod_homepage,
               "mod_sources": project.mod_sources
    }
}
